### ISSUE TITLE
Tweeting to Stephen's account

### ISSUE THREAD

**Issue by ilias-t** [stepheneyer/birdseed#3]
Don't send all tweets to Stephen Eyer's account, that's mean :smiling_imp:

**Comment by stepheneyer** [comment]
While it was fun to see everyone's creativity, the issue is now fixed. Users can now post to their own Twitter accounts instead of just mine. : ) I discovered the difference between single-user vs. multiple-user Twitter oauth and how to properly set the access token and access token secret based on user login.
